Fix buster
YunoHost-Apps/concrete5_ynh pull request #6
Opened 2020-04-16 00:15 UTC by yalh76

Fix #5

2020-04-27 11:26 UTC, maniackcrudelis commented
With the version 8.5.2, install seems ok on package_check on Buster. (Although still running...)
I also did a real install on Buster, it seems to work, I went to the admin panel.

2020-04-27 14:58 UTC, maniackcrudelis commented
Package_check ok with your last commit on Buster.

2020-05-11 22:18 UTC, yalh76 commented
Well for now, package check is ok on buster but installation fails on stretch with the error: 
```
Database should support the configured character set and collation... The database does not have a complete support for all the Unicode characters. This implies, for example, that you may not be able to save emoticons (it's the same behavior as concrete5 versions older than 8.5.0). You should upgrade your database to fix this issue.
```

2020-06-08 16:40 UTC, arthurlutz commented
Fix seems to work on my test instance, thanks for the fixes !

2020-06-08 16:49 UTC, yalh76 commented
> 
> 
> Fix seems to work on my test instance, thanks for the fixes !

and you are on Buster or Stretch ?

2020-06-08 17:35 UTC, arthurlutz commented
on buster

2020-06-09 23:02 UTC, yalh76 commented
> 
> 
> on buster

Cool, the fix works for Buster but not on Stretch... 

So maybe when YunoHost 4.0 / Buster will be released, we can merge that PR...

2020-10-18 17:51 UTC, ericgaspar requested changes

2020-10-18 17:51 UTC, ericgaspar commented on README.md
>  # concrete5_ynh
```suggestion
# Concrete5 for YunoHost
```

2020-10-18 17:51 UTC, ericgaspar approved these changes

2020-10-20 20:15 UTC, merged